apiVersion: v1
kind: Namespace
metadata:
  name: quay
  labels:
    app: quay
    argocd.argoproj.io/managed-by: openshift-gitops
    kubernetes.io/metadata.name: quay
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.24
  annotations:
    openshift.io/node-selector: ''
