ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: Database
ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
FEATURE_BUILD_SUPPORT: false
FEATURE_DIRECT_LOGIN: true
FEATURE_MAILING: false
DEFAULT_TAG_EXPIRATION: 2w
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
SERVER_HOSTNAME: quay.apps.f3a2j7vl.eastus.aroapp.io
SETUP_COMPLETE: true
SUPER_USERS:
  - quayadmin
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
    - 3y
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
