kind: QuayRegistry
apiVersion: quay.redhat.com/v1
metadata:
  name: quay-registry
  namespace: quay
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: clair
      managed: true
      overrides:
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: false
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: tls
      managed: true
    - kind: quay
      managed: true
      overrides:
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
    - kind: clairpostgres
      managed: true

